### PR TITLE
add new provider(Watch Movies Pk)

### PR DESCRIPTION
**Pull request by salman731**

### CODE REVIEW

**Comment by phisher98** [comment]
Bro why you want to add low Quality Providers ? Most of this source contains 360 to max 720p Quality

**Comment by phisher98** [comment]
Your CXXX Provider added is also not Working

**Comment by salman731** [comment]
Now it is working

**Comment by phisher98** [comment]
Okay but i can't approve this Provider its not a Quality one

**Comment by salman731** [comment]
Okay then I will remove low quality content

**Comment by salman731** [comment]
🇵🇰

Salman reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by salman731** [comment]
> Bro why you want to add low Quality Providers ? Most of this source contains 360 to max 720p Quality

Its okay if you don't want to add..

**Pull request closed without merging**
